import { Category, Product, Order, Table } from './types';

export const categories: Category[] = [
  { id: 1, name: 'Café', icon: '☕' },
  { id: 2, name: 'Té', icon: '🍵' },
  { id: 3, name: 'Pasteles', icon: '🍰' },
  { id: 4, name: 'Sándwiches', icon: '🥪' },
  { id: 5, name: 'Bebidas Frías', icon: '🧊' },
  { id: 6, name: 'Desayunos', icon: '🍳' },
];

export const products: Product[] = [
  { id: 1, name: 'Espresso', price: 35, categoryId: 1, image: '☕', description: 'Café espresso intenso', available: true },
  { id: 2, name: 'Americano', price: 40, categoryId: 1, image: '☕', description: 'Café americano clásico', available: true },
  { id: 3, name: 'Cappuccino', price: 55, categoryId: 1, image: '☕', description: 'Con espuma de leche', available: true },
  { id: 4, name: 'Latte', price: 55, categoryId: 1, image: '☕', description: 'Café con leche vaporizada', available: true },
  { id: 5, name: 'Mocha', price: 65, categoryId: 1, image: '☕', description: 'Con chocolate y crema', available: true },
  { id: 6, name: 'Macchiato', price: 50, categoryId: 1, image: '☕', description: 'Espresso manchado con leche', available: true },
  { id: 7, name: 'Té Verde', price: 35, categoryId: 2, image: '🍵', description: 'Té verde japonés', available: true },
  { id: 8, name: 'Té Negro', price: 35, categoryId: 2, image: '🍵', description: 'Earl Grey clásico', available: true },
  { id: 9, name: 'Chai Latte', price: 55, categoryId: 2, image: '🍵', description: 'Té chai con leche especiada', available: true },
  { id: 10, name: 'Manzanilla', price: 30, categoryId: 2, image: '🍵', description: 'Infusión relajante', available: true },
  { id: 11, name: 'Pastel de Chocolate', price: 75, categoryId: 3, image: '🍰', description: 'Pastel triple chocolate', available: true },
  { id: 12, name: 'Cheesecake', price: 80, categoryId: 3, image: '🍰', description: 'New York cheesecake', available: true },
  { id: 13, name: 'Croissant', price: 45, categoryId: 3, image: '🥐', description: 'Croissant de mantequilla', available: true },
  { id: 14, name: 'Muffin de Arándano', price: 50, categoryId: 3, image: '🧁', description: 'Con arándanos frescos', available: true },
  { id: 15, name: 'Tiramisú', price: 85, categoryId: 3, image: '🍰', description: 'Tiramisú italiano clásico', available: false },
  { id: 16, name: 'Club Sándwich', price: 90, categoryId: 4, image: '🥪', description: 'Pollo, tocino, lechuga y tomate', available: true },
  { id: 17, name: 'Sándwich Caprese', price: 80, categoryId: 4, image: '🥪', description: 'Mozzarella, tomate y albahaca', available: true },
  { id: 18, name: 'Panini de Jamón', price: 85, categoryId: 4, image: '🥪', description: 'Jamón serrano y queso gruyère', available: true },
  { id: 19, name: 'Wrap Vegetariano', price: 75, categoryId: 4, image: '🌯', description: 'Verduras frescas y hummus', available: true },
  { id: 20, name: 'Frappé de Café', price: 70, categoryId: 5, image: '🧊', description: 'Café helado con crema', available: true },
  { id: 21, name: 'Smoothie de Fresa', price: 65, categoryId: 5, image: '🍓', description: 'Fresa, plátano y yogur', available: true },
  { id: 22, name: 'Limonada', price: 40, categoryId: 5, image: '🍋', description: 'Limonada natural', available: true },
  { id: 23, name: 'Jugo de Naranja', price: 45, categoryId: 5, image: '🍊', description: 'Naranja recién exprimida', available: true },
  { id: 24, name: 'Chilaquiles', price: 95, categoryId: 6, image: '🍳', description: 'Con pollo y crema', available: true },
  { id: 25, name: 'Hotcakes', price: 80, categoryId: 6, image: '🥞', description: 'Con maple y mantequilla', available: true },
  { id: 26, name: 'Huevos Benedictinos', price: 110, categoryId: 6, image: '🍳', description: 'Con salsa holandesa', available: true },
  { id: 27, name: 'Omelette', price: 85, categoryId: 6, image: '🍳', description: 'Jamón, queso y champiñones', available: true },
];

export const initialTables: Table[] = [
  { id: 1, number: 1, seats: 2, status: 'available' },
  { id: 2, number: 2, seats: 2, status: 'occupied', currentOrderId: 1 },
  { id: 3, number: 3, seats: 4, status: 'available' },
  { id: 4, number: 4, seats: 4, status: 'reserved' },
  { id: 5, number: 5, seats: 6, status: 'available' },
  { id: 6, number: 6, seats: 6, status: 'occupied', currentOrderId: 2 },
  { id: 7, number: 7, seats: 4, status: 'cleaning' },
  { id: 8, number: 8, seats: 2, status: 'available' },
  { id: 9, number: 9, seats: 8, status: 'available' },
  { id: 10, number: 10, seats: 4, status: 'occupied', currentOrderId: 3 },
  { id: 11, number: 11, seats: 2, status: 'available' },
  { id: 12, number: 12, seats: 4, status: 'available' },
];

export const initialOrders: Order[] = [
  {
    id: 1,
    items: [
      { product: products[2], quantity: 2 },
      { product: products[10], quantity: 1 },
    ],
    tableNumber: 2,
    status: 'preparing',
    type: 'dine-in',
    total: 185,
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    customerName: 'María García',
  },
  {
    id: 2,
    items: [
      { product: products[15], quantity: 1 },
      { product: products[1], quantity: 1 },
      { product: products[22], quantity: 2 },
    ],
    tableNumber: 6,
    status: 'pending',
    type: 'dine-in',
    total: 220,
    createdAt: new Date(Date.now() - 1000 * 60 * 5),
    customerName: 'Carlos López',
  },
  {
    id: 3,
    items: [
      { product: products[23], quantity: 1 },
      { product: products[3], quantity: 1 },
    ],
    tableNumber: 10,
    status: 'ready',
    type: 'dine-in',
    total: 150,
    createdAt: new Date(Date.now() - 1000 * 60 * 25),
    customerName: 'Ana Martínez',
  },
  {
    id: 4,
    items: [
      { product: products[19], quantity: 2 },
      { product: products[11], quantity: 2 },
    ],
    tableNumber: null,
    status: 'delivered',
    type: 'takeaway',
    total: 300,
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
    customerName: 'Pedro Ruiz',
  },
  {
    id: 5,
    items: [
      { product: products[24], quantity: 3 },
      { product: products[0], quantity: 3 },
    ],
    tableNumber: null,
    status: 'delivered',
    type: 'takeaway',
    total: 345,
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
  },
  {
    id: 6,
    items: [
      { product: products[4], quantity: 1 },
      { product: products[12], quantity: 1 },
    ],
    tableNumber: null,
    status: 'cancelled',
    type: 'dine-in',
    total: 110,
    createdAt: new Date(Date.now() - 1000 * 60 * 180),
  },
];
